/* eslint-disable no-unused-vars */
// import images from './images';

const menu = [
  {
    image: "https://i.ibb.co/JyXxFmT/IMG-20240309-202129-removebg-preview-removebg-preview.png",
    choose: "valitse liha: nauta/kana",
    choose1: "choose meat: beef/chicken",
    title: 'KEBAB PITALEIVÄLLÄ',
    title1: 'KEBAB WITH PITA BREAD',
    price: '€9,90',
    tags: 'tomaattikastiketta | tzatzikia | tomaatti-kurkkusalaatti | pikkelöity punakaali | marinoitu punasipuli',
    tags1: 'tomato-sauce | tzatzikia | tomato-cucumber salad | pickled red cabbage | pickled red onion',
  },
  {
    image: "https://i.ibb.co/sC3Qzhp/DONER-JR-BOX-1-removebg-preview-2.png",
    choose: "valitse liha: nauta/kana",
    choose1: "choose meat: beef/chicken",
    title: 'DÖNER BOX JR',
    title1: 'DONER BOX JR',
    price: '€7,50',
    tags: 'tomaattikastiketta | ranskalaiset | ketsuppi',
    tags1: 'tomato-sauce | french | ketchup',
  },
  {
    image: "https://i.ibb.co/f8RzgM2/Kebab-Rissilaa-removebg-preview.png",
    choose: "valitse liha: nauta/kana",
    choose1: "choose meat: beef/chicken",
    title: 'KEBAB RIISILLÄ',
    title1: 'KEBAB RICE',
    price: '€10,90',
    tags: 'tomaattikastiketta | tzatzikia | tomaatti-kurkkusalaatti | pikkelöity punakaali | marinoitu punasipuli',
    tags1: 'tomato-sauce | tzatzikia | tomato-cucumber salad | pickled red cabbage | pickled red onion',
  },
  {
    image: "https://i.ibb.co/2hrSKTx/KEBAB-Ranskalaiset-removebg-preview.png",
    choose: "valitse liha: nauta/kana",
    choose1: "choose meat: beef/chicken",
    title: 'KEBAB RANSKALAISILLA',
    title1: 'KEBAB WITH FRIES',
    price: '€10,90',
    tags: 'tomaattikastiketta | tzatzikia | tomaatti-kurkkusalaatti | pikkelöity punakaali | marinoitu punasipuli',
    tags1: 'tomato-sauce | tzatzikia | tomato-cucumber salad | pickled red cabbage | pickled red onion',
  },
  {
    image: "https://i.ibb.co/PWq1sF8/RULLA-KEBAB-RULLA-KEBAB-AURAJUUSTO-TAI-FETA-removebg-preview.png",
    title: 'RULLAKEBAB',
    title1: 'RULLAKEBAB',
    price: '€11,90',
    tags: 'tomaattikastiketta | tzatzikia | tomaatti-kurkkusalaatti | pikkelöity punakaali | marinoitu punasipuli',
    tags1: 'tomato-sauce | tzatzikia | tomato-cucumber salad | pickled red cabbage | pickled red onion',
  },
  {
    image: "https://i.ibb.co/PWq1sF8/RULLA-KEBAB-RULLA-KEBAB-AURAJUUSTO-TAI-FETA-removebg-preview.png",
    choose: "valitse liha: nauta/kana",
    choose1: "choose meat: beef/chicken",
    title: 'RULLAKEBAB FETA TAI AURAJUUSTOLLA',
    title1: 'ROLLAKEBAB WITH FETA OR AURA CHEESE',
    price: '€13,90',
    tags: 'tomaattikastiketta | tzatzikia | tomaatti-kurkkusalaatti | pikkelöity punakaali | marinoitu punasipuli',
    tags1: 'tomato-sauce | tzatzikia | tomato-cucumber salad | pickled red cabbage | pickled red onion',
  },
  {
    image: "https://i.ibb.co/dWNCBx7/KANA-ISKANDER-removebg-preview.png",
    choose: "valitse liha: nauta/kana",
    choose1: "choose meat: beef/chicken",
    title: 'ISKENDER',
    title1: 'ISKENDER',
    price: '€11,90',
    tags: 'paahdettua pide-leipa kuutiota | tomaattikastiketta | tzatzikia | tomaatti-kurkkusalaatti | pikkelöity punakaali |  marinoitu punasipuli | yrtit',
    tags1: 'roasted pide-loaf cubes | tomato sauce | tzatzikia | tomato-cucumber salad | pickled red cabbage |  pickled red onion | herbs',
  },
  {
    image: "https://i.ibb.co/9Z6kqn8/TALON-SPESSU-removebg-preview.png",
    choose: "valitse proteiini: nauta/voner/falafel,ranskalaiset",
    choose1: "choose protein: beef/veal/falafel, chips",
    title: 'TALON SPESSU',
    title1: 'TALON SPESSU',
    price: '€13,50',
    tags: 'tomaattikastiketta | tzatzikia | tomaatti-kurkkusalaatti | pikkelöity punakaali | marinoitu punasipuli | hommusta | fetamurua | yrtit | paahdettua pide-leipää',
    tags1: 'tomato sauce | tzatziki | tomato and cucumber salad | pickled red cabbage | marinated red onion | hominy | feta mash | herbs | toasted pide bread',
  },
];

const pizzat = [
  {
    image: "https://i.ibb.co/wJZWxbq/PIZZA-CLASSIC-BOLOGNESE-removebg-preview-2.png",
    title: 'CLASSIC BOLOGNESE',
    title1: 'CLASSIC BOLOGNESE',
    price: '€10,20',
    tags: 'home made jauheliha kastike',
    tags1: 'home made minced meat sauce',
  },
  {
    image: "https://i.ibb.co/vjsgXHy/1-B-Margarita-1536x1024-removebg-preview-2.png",
    title: 'PIZZA MARGHERITA',
    title1: 'PIZZA MARGHERITA',
    price: '€10,80',
    tags: 'tuore tomaatti | mozzarella | rucola',
    tags1: 'fresh tomato | mozzarella | arugula',
  },
  {
    image: "https://i.ibb.co/T2bkLTw/PIZZA-Doner-special-removebg-preview-2.png",
    title: 'PIZZA DÖNER SPECIAL',
    title1: 'PIZZA DONER SPECIAL',
    price: '€12,80',
    tags: 'kebab | punasipuli | chilli | tomatti | feta',
    tags1: 'kebab | red onion | chilli | tomato | feta',
  },
  {
    image: "https://i.ibb.co/5jpP4nQ/PIZZA-NAPOLI-removebg-preview-2.png",
    title: 'PIZZA NAPOLI',
    title1: 'PIZZA NAPOLI',
    price: '€12,20',
    tags: 'katkarapu | aurajuusto | rucola',
    tags1: 'shrimp | aura cheese | arugula',
  },
  {
    image: "https://i.ibb.co/h8sJ1VT/PIZZA-CHICKEN-BBQ-removebg-preview.png",
    title: 'PIZZA CHICKEN BBQ',
    title1: 'PIZZA CHICKEN BBQ',
    price: '€12,80',
    tags: 'kana | punasipuli | mozzarella | rucola | bbq-kastike',
    tags1: 'chicken | red onion | mozzarella | arugula | bbq sauce',
  },
  {
    image: "https://i.ibb.co/S0Ks4VT/PIZZA-SALAMI-removebg-preview.png",
    title: 'PIZZA SALAMI',
    title1: 'PIZZA SALAMI',
    price: '€10,80',
    tags: 'tupla salami',
    tags1: 'double salami',
  },
  {
    image: "https://i.ibb.co/WgxzmDL/PIZZA-GREEN-DAY-removebg-preview-3.png",
    title: 'PIZZA GREEN DAY',
    title1: 'PIZZA GREEN DAY',
    price: '€10,80',
    tags: 'paprika | punasipuli | kapris | kirsikka tomaatti | rucola',
    tags1: 'paprika | red onion | capers | cherry tomato | arugula',
  },
  {
    image: "https://i.ibb.co/Ld0QNTD/PIZZA-FANTASIA-removebg-preview.png",
    title: 'PIZZA FANTASIA',
    title1: 'PIZZA FANTASIA',
    price: '€12,80',
    tags: 'oma valinta neljalla täytteellä',
    tags1: 'your choice of four fillings',
  },
  {
    image: "https://i.ibb.co/6vsNPsM/PIZZA-PEPPERONI-removebg-preview-2.png",
    title: 'PIZZA PEPPERONI',
    title1: 'PIZZA PEPPERONI',
    price: '€9,90',
    tags: 'tupla pepperoni',
    tags1: 'double pepperoni',
  },
  {
    image: "https://i.ibb.co/ry3yJ1G/Capture-removebg-preview.png",
    title: 'PIZZA MEXICANA SPECIAL',
    title1: 'PIZZA MEXICANA SPECIAL',
    price: '€12,90',
    tags: 'jauheliha | pepperoni | jalopeno | paprika | chilikastike',
    tags1: 'minced meat | pepperoni | jalopeno | paprika | chilli sauce',
  },
  {
    image: "https://i.ibb.co/J76vsZ5/PIZZA-DILLINGER-removebg-preview-2.png",
    title: 'PIZZA DILLINGER',
    title1: 'PIZZA DILLINGER',
    price: '€12,90',
    tags: 'salami | jauheliha | pepperoni | sipuli',
    tags1: 'salami | minced meat | pepperoni | onion',
  },
  {
    image: "https://i.ibb.co/WpZWJZ0/PIZZA-CHICKEN-HAWAI-2-removebg-preview.png",
    title: 'PIZZA CHICKEN HAWAII',
    title1: 'PIZZA CHICKEN HAWAII',
    price: '€11,90',
    tags: 'kana | ananas | aurajuusto',
    tags1: 'chicken | pineapple | aura cheese',
  },
  {
    image: "https://i.ibb.co/93p1FK0/PIZZA-ROMEO-1-removebg-preview-2.png",
    title: 'PIZZA ROMEO',
    title1: 'PIZZA ROMEO',
    price: '€12,90',
    tags: 'salami | ananas | aurajuusto | katkarapu',
    tags1: 'salami | pineapple | aura cheese | shrimp',
  },
];

const lisätäyttet = [
  {
    image: "https://i.ibb.co/sjvk6YM/c.jpg",
    title: 'LIHA',
    title1: 'LIHA',
    price: '€1,50',
    tags: 'pepperoni | salami | kebab | kana',
    tags1: 'pepperoni | salami | kebab | chicken',
  },
  {
    image: "https://i.ibb.co/y5GVv4d/IMG-20240507-005950-removebg-preview.png",
    title: 'KALA',
    title1: 'FISH',
    price: '€1,50',
    tags: 'katkarapu',
    tags1: 'Shrimp',
  },
  {
    image: "https://i.ibb.co/LkWqTKW/IMG-20240507-010119-removebg-preview.png",
    title: 'KASVIS',
    title1: 'KASVIS',
    price: '€1,50',
    tags: 'aura justo | ananas | olive | jelpeno | tomatti | feta',
    tags1: 'aura justo | pineapple | olive | jelpeno | tomato | feta',
  },
];

const vegeMenu = [
  {
    image: "https://i.ibb.co/85sgFGr/PITA-LEIVALLA-VONER-FALAFEL-removebg-preview-2-removebg-preview.png",
    choose: "valitse liha: vöner/falafel",
    choose1: "choose meat: kebab/falafel",
    title: 'PITALEIVÄLLÄ',
    title1: 'Pitta Bread',
    price: '€9,90',
    tags: 'tomaattikastiketta | tzatzikia | tomaatti-kurkkusalaatti | pikkelöity punakaali | marinoitu punasipuli',
    tags1: 'tomato sauce | tzatziki | tomato and cucumber salad | pickled red cabbage | marinated red onion',
  },
  {
    image: "https://i.ibb.co/44r502G/Voner-Risilla-removebg-preview.png",
    choose: "valitse liha: vöner/falafel",
    choose1: "choose meat: kebab/falafel",
    title: 'RIISILLÄ / RANSKALAISILLA',
    title1: 'WITH RICE / FRENCH FRIES',
    price: '€10,90',
    tags: 'tomaattikastiketta | tzatzikia | tomaatti-kurkkusalaatti | pikkelöity punakaali | marinoitu punasipuli',
    tags1: 'tomato sauce | tzatziki | tomato and cucumber salad | pickled red cabbage | marinated red onion',
  },
];

const salaatit = [
  {
    image: "https://i.ibb.co/HHbyYkP/Ceaser-SALATTI-r.png",
    choose: "valitse: kana / katkarapu",
    choose1: "select: chicken / shrimp",
    title: 'CAESAR SALAATTI',
    title1: 'CAESAR SALAD',
    price: '€12,90',
    tags: '',
  },
  {
    image: "https://i.ibb.co/SNG12cn/IMG-20240523-001745-removebg-preview.png",
    choose: "valitse: nauta / kana",
    choose1: "select: chicken / shrimp",
    title: 'KEBAB SALAATTI',
    title1: 'KEBAB SALAD',
    price: '€10,50',
    tags: '',
  },
  {
    image: "https://i.ibb.co/r7PcW5V/GREEK-SALATTI-removebg-preview.png",
    choose: "",
    title: 'GREEK SALAATTI',
    title1: 'GREEK SALAD',
    price: '€11,80',
    tags: 'fetajuusto | oliivi | salaatti | tomaatti | kurkku | rucola | pestokastike',
    tags1: 'feta cheese | olives | lettuce | tomato | cucumber | rocket | pesto sauce',
  },
];

const extrat2 = [
  {
    image: "https://i.ibb.co/fMPY1TG/TUPLA-LIHA-Nauta-kana-removebg-preview.png",
    choose: "",
    choose1: "",
    title: 'TUPLALIHA KANA',
    title1: 'TUPLALIHA CHICKENS',
    price: '€4,00',
    tags: '',
    tags1: '',
  },
  {
    image: "https://i.ibb.co/Yp4XSTN/Aura-juusto-Feta.jpg",
    choose: "",
    choose1: "",
    title: 'JUSTO / AURA / FETA',
    title1: 'JUSTO / AURA / FETA',
    price: '€2,00',
    tags: '',
    tags1: '',
  },
  {
    image: "https://i.ibb.co/w7YxYk2/IMG-20240507-012211.jpg",
    choose: "",
    choose1: "",
    title: 'RANSKA',
    title1: 'French fries',
    price: '€3,50',
    tags: '',
    tags1: '',
  },
  {
    image: "https://i.ibb.co/XVxCbP9/IMG-20240507-012228.jpg",
    choose: "",
    choose1: "",
    title: 'VÖNER / FALAFEL',
    title1: 'KEBAB / FALAFEL',
    price: '€4,00',
    tags: '',
    tags1: '',
  },
  {
    image: "https://i.ibb.co/S3hdXGr/IMG-20240507-012308-removebg-preview-2.png",
    choose: "",
    choose1: "",
    title: 'Gluteeniton Pizzapohja',
    title1: 'Gluten Free Pizza Crust',
    price: '€3,00',
    tags: '',
    tags1: '',
  },

];

const drinks = [
  {
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3MpMqT1q2rr7-lkBgm9iAqnuDmKUHTzVqd3Om-5jYig&s",
    choose: "",
    title: 'Coca - cola ------- 330ml/500ml/1.5L',
    price: '€2,50/4,00/6,00',
    tags: '',
  },
  {
    image: "https://assets.superliquor.co.nz/thumbs/0007813.jpeg",
    choose: "",
    title: 'Coca-cola zero ----- 330ml/500ml/1.5L',
    price: '€2,50/4,00/6,00',
    tags: '',
  },
  {
    image: "https://target.scene7.com/is/image/Target/GUEST_d20d55ba-2140-40ce-9899-484a25ba090c?wid=488&hei=488&fmt=pjpeg",
    choose: "",
    title: 'Sprite zero - 330ml',
    price: '€2,50',
    tags: '',
  },
  {
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtrgyNLdQ2emYrkqXv_cyqUZY7XJGOlz2bNmoOGUGY3Q&s",
    choose: "",
    title: 'Fanta (applesini) - 330ml',
    price: '€2,50',
    tags: '',
  },
  {
    image: "https://assets.superliquor.co.nz/thumbs/0005404.jpeg",
    choose: "",
    title: 'Fanta - 500ml',
    price: '€4,00',
    tags: '',
  },
]

export default { menu, pizzat, lisätäyttet, vegeMenu, salaatit, extrat2, drinks };
